### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by 1allen** [albaraam/yii2-gcm-apns#1]
> composer require albaraam/yii2-gcm-apns "~1.0.0"
> ...
> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
> - albaraam/php-gcm-apns v1.0.0 requires duccio/apns-php dev-master -> no matching package found.
> - albaraam/yii2-gcm-apns v1.0.0 requires albaraam/php-gcm-apns ~1.0.0@dev -> satisfiable by albaraam/php-gcm-apns[v1.0.0].
> - Installation request for albaraam/yii2-gcm-apns ~1.0.0 -> satisfiable by albaraam/yii2-gcm-apns[v1.0.0].

the `duccio/apns-php` dependency in `albaraam/php-gcm-apns` seems to be specified correctly, so I've no idea how to fix it :(

**Comment by 1allen** [comment]
oh, I'm sorry — this error occurs because of `"minimum-stability": "stable"` in my `composer.json`.
However I'll try to contact duccio, thank you!

**Comment by albaraam** [comment]
That's right, actually I think, if necessary,  you can leave it `"minimum-stability": "stable"` and add the library manually `"duccio/apns-php": "dev-master"` to the require section
